export const data = [
    {
        address: 'dr. melo 2833',
        name: 'od. carlos costoya',
        neighbourhood: 'lanus',
        city: 'bsas',
        tel: '5491142416334',
    },
    {
        address: 'bonpland 2376 piso 1 a',
        name: 'od. juliana saunders',
        neighbourhood: 'palermo',
        city: 'caba',
        whatsapp: '5491167083728',
    },
    {
        address: 'santa Fe 3444 piso 10 a',
        name: 'consultorio drs. peclman',
        neighbourhood: 'palermo',
        city: 'caba',
        whatsapp: '5491169773011',
    },
    {
        address: 'arenales 1961 piso 7 b',
        name: 'od. romina vivanco',
        neighbourhood: 'recoleta',
        city: 'caba',
        whatsapp: '5491160301443',
    },
    {
        address: 'velez sarfield 4498, munro',
        name: 'cityDent',
        neighbourhood: 'vicente lópez',
        city: 'bsas',
        whatsapp: '5491124896434',
    },
    {
        address: 'migueletes 863 4D',
        name: 'od. laura randano',
        neighbourhood: 'palermo',
        city: 'caba',
        whatsapp: '5491161125342',
    },
    {
        address: 'virrey del pino 2328 piso 3',
        name: 'od. fiorella chicata lopez',
        neighbourhood: 'belgrano',
        city: 'caba',
        whatsapp: '5491159525435',
    },
    {
        address: 'Portela 338',
        name: 'od. ayelen beron',
        neighbourhood: 'lomas de zamora',
        city: 'bsas',
        whatsapp: '5491123918422',
    },
]